### ISSUE TITLE
Api always returning 400 BAD REQUEST when authenticating

### ISSUE THREAD

**Issue by hackaprende** [starlock/vino#17] opened 2015-11-01 07:26 UTC
When I try make a post to https://api.vineapp.com/users/authenticate I always get a 400 BAD REQUEST:

{
code: 101
data: ""
success: false
error: "That username or password is incorrect."
}

I have tried with different emails and passwords, am I doing something wrong?

**Comment by hult** [comment] 2015-11-02 08:35
Well, the error message seems to suggest you're not using valid username/password combinations (?).

**Comment by hackaprende** [comment] 2015-11-02 16:08
The weird thing is I have tried with three different accounts and I get the same response. I am sure I am using the correct username/password.

**Comment by levantAJ** [comment] 2016-01-05 09:46
Waiting for the answer :( Any solutions?

**Comment by hult** [comment] 2016-04-11 14:46
I can't reproduce this, `Vine().login(username, password)` works just fine. Closing.

**Closed as completed by hult** 2016-04-11 14:46 UTC
